<?php

/**
 * @file
 * Provides a my product entity type.
 */

use Drupal\Core\Render\Element;
use Drupal\my_product\Entity\MyProduct;
use Drupal\user\UserInterface;

/**
 * Implements hook_theme().
 */
function my_product_theme() {
  return [
    'my_product' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for my product templates.
 *
 * Default template: my-product.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the my product information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_my_product(array &$variables) {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_user_cancel().
 */
function my_product_user_cancel($edit, UserInterface $account, $method) {
  switch ($method) {
    case 'user_cancel_block_unpublish':
      // Unpublish my products.
      $storage = \Drupal::entityTypeManager()->getStorage('my_product');
      $my_product_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->condition('status', 1)
        ->execute();
      foreach ($storage->loadMultiple($my_product_ids) as $my_product) {
        $my_product->set('status', FALSE);
        $my_product->save();
      }
      break;

    case 'user_cancel_reassign':
      // Anonymize my products.
      $storage = \Drupal::entityTypeManager()->getStorage('my_product');
      $my_product_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->execute();
      foreach ($storage->loadMultiple($my_product_ids) as $my_product) {
        $my_product->setOwnerId(0);
        $my_product->save();
      }
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete() for user entities.
 */
function my_product_user_predelete(UserInterface $account) {
  // Delete my products.
  $storage = \Drupal::entityTypeManager()->getStorage('my_product');
  $my_product_ids = $storage->getQuery()
    ->condition('uid', $account->id())
    ->execute();
  $my_products = $storage->loadMultiple($my_product_ids);
  $storage->delete($my_products);
}
