<?php

use Symfony\Component\HttpFoundation\RedirectResponse;
use Drupal\Core\Url;

function my_module_theme($existing, $type, $theme, $path) {
    return [
        'my-module-template' => [
            'variables' => ['test_var' => NULL],
        ],
    ];
}

/**
 * Implements hook_user_login().
 */

function my_module_user_login($account) {
    $roles = $account->getRoles();
    if(in_array('moderator', $roles)){
    $response = new RedirectResponse('/admin/content');
    $response->send();
    return;
  }
}