favicon:
  mimetype: image/jpeg
  path: 'public://news-3.jpg'
  url: 'http://drupal.localhost/themes/contrib/bootstrap/favicon.ico'
  use_default: 1
features:
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
  node_user_picture: 1
logo:
  path: 'public://145-1451186_exclusive-news-my-next-move-logo.png'
  url: ''
  use_default: 1
schemas:
  bootstrap: 8000
  beetroot_example_theme: 8000
reset_http_request_cache: ''
table: ''
