_core:
  default_config_hash: cpiebjeL5BJQM1KnuVUE-HxHiY-5OM6jfuhD1-SLNU0
show_node: true
show_block: true
placement: before
size: 16x12
path: 'modules/contrib/languageicons/flags/*.png'
show: null
actions: null
form_build_id: form-wDn3PBDuR3BscY-B0OmrFPfKuJiPvTXa_mza7bNuif0
form_token: V4tDA5m1nvU7XY0cK504TJM3S4CUOAIULKp1b-i-bh0
form_id: languageicons_settings
