<?php

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\node\NodeInterface;
/**
 * Implements hook_ENTITY_TYPE_view_alter().
 */
function glossary_tooltip_node_view_alter(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display)
{
  if (!$entity instanceof NodeInterface
    || !$entity->hasField('body')
    || $entity->get('body')->isEmpty()
  ) {
    return;
  }

  $body = $entity->get('body')->value;
  $termStorage = \Drupal::entityTypeManager()->getStorage('taxonomy_term');
  $ids = $termStorage->getQuery()
    ->condition('vid', 'glossary_tooltip')
    ->execute();

  $vocabulary = [];
  foreach ($termStorage->loadMultiple($ids) as $item) {
    $vocabulary[$item->id()] = ["name" => $item->label(),
      "body" => $item->get("description")->value];
  }

  foreach ($vocabulary as $term) {
    $description = strip_tags($term["body"], $allowed_tags = null);
    $name_term = $term["name"];
    $body = str_replace($name_term, "<a title=\"$description\">$name_term</a>", $body);
  }
  if ($build['#view_mode'] == 'full' && isset($build['body'])) {
    $build['body'] = [
      '#type' => 'container',
      '#weight' => 5,
      '#attributes' => [
        'class' => ['body_glossary_tooltip'],
      ],
    ];
    $build['field__item']['p'] = [
      '#type' => 'html_tag',
      '#tag' => 'p',
      '#value' => $body,
    ];
  }
    return $build;

  }


